const { spawn } = require('child_process');
const fs = require('fs'), assert = require('assert'), path = require('path'), os = require('os');
const root = fs.mkdtempSync(path.join(os.tmpdir(), 'local-workspace-test-'));
const dir = path.join(root, 'sample_space'); fs.mkdirSync(dir);
const fixture = path.join(dir, 'fixture.txt');
const exe = process.env.WORKSPACE_TEST_EXE || path.join(__dirname, '../dist-next/LocalWorkspace.exe');
const child = spawn(exe, ['--mcp'], {windowsHide:true,stdio:['pipe','pipe','pipe'],env:{...process.env,WORKSPACE_STATE_DIR:path.join(root,'.state')}});
let seq = 0, buffer = ''; const pending = new Map(), notifications=[];
child.stdout.on('data', d => { buffer += d; let at; while ((at = buffer.indexOf('\n')) >= 0) { const msg = JSON.parse(buffer.slice(0, at)); buffer = buffer.slice(at + 1); if(msg.method)notifications.push(msg); const p = pending.get(msg.id); if (p) { pending.delete(msg.id); p(msg); } } });
child.stderr.resume();
const request = (method, params = {}) => new Promise(resolve => { const id = ++seq; pending.set(id, resolve); child.stdin.write(JSON.stringify({ jsonrpc: '2.0', id, method, params }) + '\n'); });
const validators = new Map(), ajv = new (require('ajv'))({ strict: false });
const call = async (name, args) => { const r = await request('tools/call', { name, arguments: args }); assert(!r.error, JSON.stringify(r)); const validate=validators.get(name); if(validate)assert(validate(r.result.structuredContent), name+': '+JSON.stringify(validate.errors)); return r.result; };
async function main() {
  assert.equal((await request('initialize', { protocolVersion: '2025-06-18', capabilities: {}, clientInfo: { name: 'test', version: '1' } })).result.serverInfo.name, 'local-workspace');
  const list = await request('tools/list'); assert.equal(list.result.tools.length, 28); assert.equal(list.result.tools.filter(t=>t._meta.ui?.resourceUri).length,0); assert(list.result.tools.every(t=>t.outputSchema&&t._meta['openai/toolInvocation/invoking']));assert(list.result.tools.every(t=>!t.icons),'legacy tools/list must stay icon-free for ChatGPT security validation');
  for(const tool of list.result.tools)validators.set(tool.name,ajv.compile(tool.outputSchema));
  assert((await request('resources/read', { uri: 'ui://local-workspace/review-v5.html' })).error);
  assert(!(await call('write_file', { path: fixture, content: '第一行\nsecond\n' })).isError); assert((await call('write_file', { path: fixture, content: 'no' })).isError);
  const edit = await call('edit_file', { path: fixture, old_text: 'second', new_text: 'edited' }); assert(!edit.isError); assert.equal(edit.structuredContent.result.diff.added, 1); assert.equal(edit.structuredContent.result.diff.removed, 1);
  assert((await call('edit_file', { path: fixture, old_text: 'missing', new_text: 'no' })).isError);
  assert.equal((await call('read_file', { path: fixture, start_line: 1, limit: 1 })).structuredContent.result.next_line, 2);
  const run = (await call('exec_command', { shell: 'powershell', command: "Start-Sleep -Milliseconds 400; Write-Output 'command-ok'", cwd: dir, yield_ms: 0 })).structuredContent.result;
  let output = ''; for (let i = 0; i < 10; i++) { const snap = (await call('poll_command', { session_id: run.session_id, yield_ms: 1000 })).structuredContent.result; output += snap.output; if (!snap.running) { assert.equal(snap.exit_code, 0); break; } } assert(output.includes('command-ok'));
  assert.equal((await call('show_changes', { path: dir })).structuredContent.result.count, 1); assert.equal((await request('bogus')).error.code, -32601);
  console.log('PASS protocol, 28 tools, read/write/edit, diff, review, command polling');
  const escaped = path.join(root, 'sample', '_space');
  for (const target of [dir, dir.replaceAll('\\', '/'), escaped]) { const r = await call('list_directory', { path: target, limit: 3 }); assert(!r.isError); assert.equal(r.structuredContent.result.entries.length, 1); assert.equal(r.structuredContent.result.path, dir.replaceAll('\\', '/')); }
  const missing = await call('list_directory', { path: path.join(root, 'missing') }); assert(missing.isError); assert.equal(missing.structuredContent.result.error_code, 'PATH_NOT_FOUND');
  const beyond = await call('list_directory', { path: dir, offset: 99999 }); assert.equal(beyond.structuredContent.result.empty, false); assert.equal(beyond.structuredContent.result.returned_count, 0);
  assert((await call('write_file', { path: path.join(escaped, 'fixture.txt'), content: 'wrong', overwrite: true })).isError); assert(fs.readFileSync(fixture, 'utf8').includes('edited'));
  const empty = path.join(root, 'empty'); fs.mkdirSync(empty); assert.equal((await call('list_directory', { path: empty })).structuredContent.result.empty, true); assert(!(await call('list_directory', { path: dir, limit: null })).isError);
  console.log('PASS portable directory fixtures, escaped underscore, absent vs empty, pagination, write identity');
  assert(!(await call('write_file', { path: fixture, content: 'one\ntwo\nthree', overwrite: true })).isError);
  const multi = await call('edit_file', { path: fixture, old_text: 'one\ntwo\nthree', new_text: 'ONE\ntwo\nTHREE' }); assert.equal(multi.structuredContent.result.diff.added, 2); assert.equal(multi.structuredContent.result.diff.removed, 2);
  fs.writeFileSync(fixture, Buffer.concat([Buffer.from([0xef, 0xbb, 0xbf]), Buffer.from('bom-text')])); assert(!(await call('edit_file', { path: fixture, old_text: 'bom-text', new_text: 'bom-updated' })).isError); assert(fs.readFileSync(fixture).subarray(0, 3).equals(Buffer.from([0xef, 0xbb, 0xbf])));
  const timeout = (await call('exec_command', { shell: 'powershell', command: 'Start-Sleep -Seconds 15', cwd: dir, yield_ms: 0, timeout_seconds: 1 })).structuredContent.result;
  await new Promise(r => setTimeout(r, 1800)); const timed = (await call('poll_command', { session_id: timeout.session_id, yield_ms: 1000 })).structuredContent.result; assert.equal(timed.timed_out, true); assert.equal(timed.running, false);
  console.log('PASS multiline diff, BOM preservation and unattended timeout');
  const nested = path.join(dir, '中文 空格'); fs.mkdirSync(nested); fs.writeFileSync(path.join(nested, 'sample.cs'), 'first\nFind This Text\nlast');
  assert.equal((await call('search_files', { path: dir, pattern: '*.cs' })).structuredContent.result.matches.length, 1);
  assert.equal((await call('search_text', { path: dir, query: 'find this', pattern: '*.cs' })).structuredContent.result.matches[0].line, 2);
  assert.equal((await call('search_text', { path: dir, query: 'find this', case_sensitive: true })).structuredContent.result.matches.length, 0);
  assert.equal((await call('search_files', { path: dir, pattern: '*.cs', recursive: false })).structuredContent.result.matches.length, 0);
  assert.equal((await call('file_info', { path: fixture })).structuredContent.result.size_bytes, fs.statSync(fixture).size);
  console.log('PASS filename/content search, case sensitivity, recursion, Unicode/spaces and file metadata');
  const status=(await call('get_workspace_status',{})).structuredContent.result;assert.equal(status.version,'2.3.0');assert.equal(status.tool_count,28);assert(status.tools.includes('write_stdin'));assert(status.activity.some(x=>x.status==='failed'));
  const created=path.join(root,'new','nested');assert((await call('create_directory',{path:created})).structuredContent.result.created);assert.equal((await call('create_directory',{path:created})).structuredContent.result.created,false);
  const live=(await call('exec_command',{shell:'powershell',command:"Write-Output 'first-output'; Start-Sleep -Seconds 2; Write-Output 'last-output'",cwd:dir,yield_ms:1000})).structuredContent.result;
  const snap1=(await call('read_command',{session_id:live.session_id})).structuredContent.result;assert(snap1.full_output.includes('first-output'));assert.equal(snap1.output_mode,'snapshot');
  const finished=(await call('poll_command',{session_id:live.session_id,yield_ms:4000})).structuredContent.result;assert(finished.output.includes('last-output'));assert(!finished.running);
  const snap2=(await call('read_command',{session_id:live.session_id})).structuredContent.result;assert(snap2.output.includes('first-output')&&snap2.output.includes('last-output'));
  const failed=await call('exec_command',{shell:'powershell',command:"Write-Output 'before-failure'; exit 7",cwd:dir,yield_ms:4000});assert(failed.isError);assert.equal(failed.structuredContent.result.exit_code,7);assert(failed.structuredContent.result.output.includes('before-failure'));
  const shellError=await call('exec_command',{shell:'powershell',command:"Get-Item -LiteralPath 'definitely-missing-fixture'",cwd:dir,yield_ms:4000});assert(shellError.isError);
  const stoppable=(await call('exec_command',{shell:'powershell',command:'Start-Sleep -Seconds 30',cwd:dir,yield_ms:0})).structuredContent.result;
  const stopped=await call('stop_command',{session_id:stoppable.session_id});assert(!stopped.isError);assert(stopped.structuredContent.result.stopped);assert(!stopped.structuredContent.result.running);
  const sessionList=(await call('list_commands',{})).structuredContent.result;assert(sessionList.commands.some(c=>c.session_id===live.session_id&&!c.running));
  const input=(await call('exec_command',{shell:'powershell',command:"$line=[Console]::ReadLine(); Write-Output ('received:'+ $line)",cwd:dir,yield_ms:0})).structuredContent.result;
  assert(!(await call('write_stdin',{session_id:input.session_id,text:'input-ok\n',close:true})).isError);
  const inputResult=(await call('poll_command',{session_id:input.session_id,yield_ms:4000})).structuredContent.result;assert(inputResult.full_output.includes('received:input-ok'));
  const tracked=await request('tools/call',{name:'exec_command',arguments:{shell:'powershell',command:'Start-Sleep -Seconds 3',cwd:dir,yield_ms:4000},_meta:{progressToken:'test-progress'}});assert(!tracked.result.isError);const progress=notifications.filter(n=>n.params?.progressToken==='test-progress');assert(progress.length>=3);assert(progress.every((n,i)=>!i||n.params.progress>progress[i-1].params.progress));
  console.log('PASS diagnostics, directory creation, non-consuming live output, failures, stop, stdin and progress');
  const imagePath=path.join(root,'pixel.png'),imageBytes=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+aXioAAAAASUVORK5CYII=','base64');fs.writeFileSync(imagePath,imageBytes);const pic=await call('read_image',{path:imagePath});assert.equal(pic.content[1].mimeType,'image/png');assert(Buffer.from(pic.content[1].data,'base64').equals(imageBytes));assert((await call('read_image',{path:fixture})).isError);
  const {execFileSync}=require('child_process');const repo=path.join(root,'git-fixture');fs.mkdirSync(repo);const git=(...args)=>execFileSync('git',args,{cwd:repo,windowsHide:true,stdio:'pipe'});git('init','-q');fs.writeFileSync(path.join(repo,'file.txt'),'before\n');git('add','file.txt');git('-c','user.name=Fixture','-c','user.email=fixture@example.invalid','commit','-qm','fixture');fs.writeFileSync(path.join(repo,'file.txt'),'after\n');const gitStatus=await call('git_status',{path:repo});assert(gitStatus.structuredContent.result.output.includes('file.txt'),JSON.stringify(gitStatus));const diff=(await call('git_diff',{path:repo})).structuredContent.result;assert(diff.output.includes('-before')&&diff.output.includes('+after'));git('add','file.txt');assert((await call('git_diff',{path:repo,staged:true})).structuredContent.result.output.includes('+after'));assert((await call('git_status',{path:dir})).isError);
  const sub=path.join(repo,'nested');fs.mkdirSync(sub);fs.writeFileSync(path.join(repo,'AGENTS.md'),'root guidance');fs.writeFileSync(path.join(sub,'AGENTS.md'),'ignored');fs.writeFileSync(path.join(sub,'AGENTS.override.md'),'nested override');
  const context=(await call('open_workspace',{path:sub})).structuredContent.result;assert.equal(context.git_root,repo.replaceAll('\\','/'));assert(context.instructions.some(x=>x.content==='root guidance'));assert(context.instructions.some(x=>x.content==='nested override'));assert(!context.instructions.some(x=>x.content==='ignored'));
  const plan=[{step:'Verify fixture',status:'in_progress'},{step:'Finish',status:'pending'}];assert(!(await call('update_plan',{path:sub,plan})).isError);assert.deepEqual((await call('open_workspace',{path:sub})).structuredContent.result.plan.plan.map(({step,status})=>({step,status})),plan);assert((await call('update_plan',{path:sub,plan:[...plan,{step:'Invalid parallel',status:'in_progress'}]})).isError);
  assert((await call('exec_command',{cwd:dir,shell:'powershell',cmd:'echo no',tty:true})).isError);assert((await call('exec_command',{cwd:dir,shell:'powershell',cmd:'echo one',command:'echo two'})).isError);
  const raw=(await call('exec_command',{cwd:dir,shell:'powershell',cmd:"[Console]::Write('no-newline'); Start-Sleep -Seconds 3",yield_time_ms:1000})).structuredContent.result;assert(raw.running);assert(raw.output.includes('no-newline'));const rawDone=(await call('write_stdin',{session_id:raw.session_id,yield_time_ms:4000})).structuredContent.result;assert(!rawDone.running);assert.equal(rawDone.exit_code,0);
  if(context.shells.some(x=>x.name==='git_bash'&&x.available)){const bash=await call('exec_command',{cwd:dir,shell:'bash',cmd:"printf '%s' 'quoted \"value\" and spaces'",yield_time_ms:4000});assert(!bash.isError);assert.equal(bash.structuredContent.result.output,'quoted "value" and spaces');}
  const defaultBash=await call('exec_command',{cwd:nested,cmd:"printf '%s\\n' \"$BASH_VERSION\"; pwd; printf '%s' '中文'",yield_time_ms:4000});assert(!defaultBash.isError);assert.equal(defaultBash.structuredContent.result.shell,'git_bash');assert(defaultBash.structuredContent.result.output.includes('中文'));assert(defaultBash.structuredContent.result.output.includes('中文 空格'));assert(defaultBash.structuredContent.result.shell_executable.endsWith('/bin/bash.exe'));assert.equal(context.default_shell,'git_bash');
  const bashInput=(await call('exec_command',{cwd:dir,cmd:"read -r line; printf 'received:%s' \"$line\"",yield_time_ms:0})).structuredContent.result;await call('write_stdin',{session_id:bashInput.session_id,chars:'bash-input\n',close:true});const bashInputDone=(await call('write_stdin',{session_id:bashInput.session_id,yield_time_ms:4000})).structuredContent.result;assert(bashInputDone.full_output.includes('received:bash-input'));assert.equal(bashInputDone.shell,'git_bash');
  const bashFail=await call('exec_command',{cwd:dir,cmd:'exit 9',yield_time_ms:4000});assert(bashFail.isError);assert.equal(bashFail.structuredContent.result.exit_code,9);
  console.log('PASS default Git Bash, Unicode cwd/output, stdin, shell identity and failure status');
  console.log('PASS workspace instruction precedence, plan state, aliases, pipe output without newline and shell selection');
  console.log('PASS native image content, Git external changes, staged diff and non-repository errors');
}
const watchdog = setTimeout(() => { child.kill(); console.error('Test timed out'); process.exitCode = 2; }, 60000);
main().catch(e => { console.error(e); process.exitCode = 1; }).finally(() => { clearTimeout(watchdog); child.stdin.end(); });
child.on('exit', () => fs.rmSync(root, { recursive: true, force: true }));
